### ISSUE TITLE
onClick event

### ISSUE THREAD

**Issue by RabinMallick** [NiklasKnaack/jquery-svg3dtagcloud-plugin#7]
Hi,
I need to use onClick event on the icons click.
Is there any built in functionality?

Or could you help with this?

**Comment by NiklasKnaack** [comment]
Hi,
in the current form, the elements of the cloud only work with href links that are set via setAttribute.

**Comment by RabinMallick** [comment]
Hi,
Found a workaround

 $("#holder svg a").on('click', function (event){
      console.log(event.target);
    });
    
    Thanks for your quick response.
